services:

  python:
    container_name: python
    build:
      context: ./scripts/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - IS_DOCKERISED=1
      - IS_PRODUCTION=1
    env_file:
      - ./scripts/.env
    networks:
      - headcount

  server:
    container_name: server
    build:
      context: ./headcount-backend/api
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - ./headcount-backend/api/src/db/database.db:/app/src/db/database.db
    env_file:
      - ./headcount-backend/api/.env
    ports:
      - 8080:3000
    networks:
      - headcount

  web:
    container_name: web
    build:
      context: ./headcount-backend/web
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - ./headcount-backend/web/.env
    environment:
      - IS_DOCKERISED=1
    ports:
      - 5173:5173
    networks:
      - headcount

networks:
  headcount:
    name: headcount

