
services:

  python:
    container_name: python
    build:
      context: ./scripts/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - IS_DOCKERISED=1
    env_file:
      - ./scripts/.env

  server:
    container_name: server
    build:
      context: ./headcount-backend/api
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    env_file:
      - ./headcount-backend/api/.env
    ports:
      - 8080:3000
