
services:

  python:
    container_name: headcount-python
    build:
      context: ./scripts/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - IS_DOCKERISED=1
    env_file:
      - ./scripts/.env
    networks:
      - headcount
      - global-network

  server:
    container_name: headcount-server
    build:
      context: ./headcount-backend/api
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    volumes:
      - ./headcount-backend/api/src/db/database.db:/app/src/db/database.db
    env_file:
      - ./headcount-backend/api/.env
    networks:
      - headcount
      - global-network

  web:
    container_name: headcount-web
    build:
      context: ./headcount-backend/web
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - ./headcount-backend/web/.env
    environment:
      - IS_DOCKERISED=1
      - HOST=0.0.0.0
      - PORT=5173
    networks:
      - headcount
      - global-network

networks:
  headcount:
    name: headcount

  global-network:
    external: true
