name: build-server

on:
  push:
    branches:
      - main
    paths:
      - headcount-backend/server/**

  workflow_dispatch:

jobs:
  push_web_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}

    - name: Build and publish new web image
      uses: docker/build-push-action@v6
      with:
        context: headcount-backend/api
        tags: ghcr.io/kakajuro/headcount-server:latest
        push: true
